services:
  app:
    # exclude_from_hc: true
    build:
      context: .
    volumes:
      - .:/app
  web:
    # exclude_from_hc: true
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
