import { configDotenv } from "dotenv";
configDotenv();

// Command and index files are generated by the CLI...
// Run `discraft dev` or `discraft build` to generate them
import { Events, PermissionFlagsBits, formatEmoji } from "discord.js";
import { registerCommands } from "./.discraft/commands/index";
import { registerEvents } from "./.discraft/events/index";
import client from "./clients/discord";
import { analytics } from "./utils/analytics/index";
import { logger } from "./utils/logger";

const CAPYBARA_EMOJI_NAME = "capybara";
const CAPYBARA_EMOJI_ID = "1515518843420676136";

async function checkCapybaraEmojiSetup() {
  if (!client.application) {
    logger.warn("Cannot check capybara emoji setup because the application is unavailable.");
    return;
  }

  const emoji = await client.application.emojis.fetch(CAPYBARA_EMOJI_ID).catch(() => null);

  if (emoji) {
    logger.success(
      `Capybara emoji found: ${formatEmoji(emoji.id, emoji.animated)}. The system prompt will tell CapyBot to use it for capybara emoji needs.`,
    );
  } else {
    logger.warn(
      `No application emoji found with ID ${CAPYBARA_EMOJI_ID}. Upload a custom capybara emoji in the Discord Developer Portal for this application, name it "${CAPYBARA_EMOJI_NAME}", update CAPYBARA_EMOJI_ID if the ID changed, then restart CapyBot.`,
    );
  }

  const missingGuilds = client.guilds.cache.filter((guild) => {
    const member = guild.members.me;
    return !member?.permissions.has(PermissionFlagsBits.UseExternalEmojis);
  });

  if (missingGuilds.size === 0) {
    logger.success("CapyBot has Use External Emojis permission in every cached server.");
    return;
  }

  logger.warn(
    `CapyBot is missing Use External Emojis permission in: ${missingGuilds.map((guild) => guild.name).join(", ")}. Give the bot role the "Use External Emojis" permission in those servers/channels.`,
  );
}

logger.start("Starting bot...");

analytics.initialize().catch((err) => {
  logger.error("Failed to initialize analytics system.");
  logger.verbose(err);
});

// Register events before login
registerEvents(client)
  .then(() => {
    logger.verbose("Events registered in main process.");
  })
  .catch((err) => {
    logger.error("Error registering events.");
    logger.verbose(err);
  })
  .finally(() => {
    client.on(Events.ClientReady, async () => {
      logger.success("Client logged in.");
      try {
        await registerCommands(client);
        await checkCapybaraEmojiSetup();
      } catch (err) {
        logger.error("Error registering commands.");
        logger.verbose(err);
      }
    });
    client.login(process.env.DISCORD_TOKEN).catch((err) => {
      logger.error("Client login failed, make sure your token is set correctly.");
      logger.verbose(err);
    });
  });

process.on("uncaughtException", (err) => {
  logger.error("Uncaught exception.");
  logger.verbose(err);
});

process.on("unhandledRejection", (err) => {
  logger.error("Unhandled rejection.");
  logger.verbose(err);
});

process.on("SIGINT", async () => {
  logger.info("Received SIGINT, Gracefully shutting down...");
  try {
    logger.info("Closing client...");
    await client.destroy();
    logger.success("Client closed.");
  } catch (err) {
    logger.error("Error while shutting down client.");
    logger.verbose(err);
  }
  logger.info("Exiting...");
  process.exit(0);
});
