[phases.setup]
pkgs = ["nodejs_23"]
aptPkgs = ["python3", "g++", "make"]

[phases.install]
cmds = ["npm install --frozen-lockfile"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx discraft start --runner node"
